package ifneeded fpgaedu::json 2.0 [list source [file join $dir json.tcl]]
package ifneeded fpgaedu::jsonrpc 1.0 [list source [file join $dir jsonrpc.tcl]]
package ifneeded fpgaedu::assert 1.0 [list source [file join $dir assert.tcl]]
package ifneeded fpgaedu::assert::json 1.0 [list source [file join $dir assertjson.tcl]]
package ifneeded fpgaedu::vivado 1.0 [list source [file join $dir vivado.tcl]]