package ifneeded fpgaedu::json 2.0 [list source [file join $dir json.tcl]]
package ifneeded fpgaedu::jsonrpc 1.0 [list source [file join $dir jsonrpc.tcl]]
package ifneeded fpgaedu::vivado 1.0 [list source [file join $dir vivado.tcl]]
package ifneeded fpgaedu::vivadoserver 1.0 [list source [file join $dir vivadoserver.tcl]]
package ifneeded fpgaedu::test::assert 1.0 [list source [file join $dir test assert.tcl]]
package ifneeded fpgaedu::test::constraint 1.0 [list source [file join $dir test constraint.tcl]]
